//code to wait for the DOM content to be loaded using DOMContentLoaded event.
document.addEventListener("DOMContentLoaded", function () {
    //selecting the color-box and change-color-btn elements using document.getElementById().
    let btn=document.getElementById("change-color-btn");
    let box=document.getElementById("color-box");
    /* creating getRandomColor() function which generates a random color using hexadecimal */
    function getRandomColor() {
        return "#" + Math.floor(Math.random() * 16777215).toString(16).padStart(6, "0");
    }
    /*event listener to the change-color-btn element. When clicked, the event listener should trigger a function that changes the background color of the color-box to a random color generated by the getRandomColor() function.*/
    btn.addEventListener("click",function(){
        box.style.backgroundColor = getRandomColor();
    })
})
